default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: twitter_clone_2019_development

test:
  <<: *default
  database: twitter_clone_2019_test

production:
  <<: *default
  database: twitter_clone_2019_production
